/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UASPBO;

import java.awt.Color;

/**
 *
 * @author RIO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSkripsi = new javax.swing.JButton();
        jButtonBuku = new javax.swing.JButton();
        jButtonBuku1 = new javax.swing.JButton();
        jButtonAnggota = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN UINSA");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jButtonSkripsi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSkripsi.setText("SKRIPSI");
        jButtonSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkripsiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSkripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 176, 80));

        jButtonBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBuku.setText("BUKU");
        jButtonBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBukuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 176, 80));

        jButtonBuku1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBuku1.setText("PINJAM");
        jButtonBuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuku1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 176, 80));

        jButtonAnggota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAnggota.setText("ANGGOTA");
        jButtonAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 176, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perpus.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentHidden

    private void jButtonSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkripsiActionPerformed
        // TODO add your handling code here:
        TampilSkripsi frameSkripsi = new TampilSkripsi();
        frameSkripsi.setVisible(true); 
    }//GEN-LAST:event_jButtonSkripsiActionPerformed

    private void jButtonBuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuku1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuku1ActionPerformed

    private void jButtonAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnggotaActionPerformed
        TampilAnggota frameAnggota = new TampilAnggota();
        frameAnggota.setVisible(true);
    }//GEN-LAST:event_jButtonAnggotaActionPerformed

    private void jButtonBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBukuActionPerformed
        TampilBuku frameBuku = new TampilBuku();
        frameBuku.setVisible(true);
    }//GEN-LAST:event_jButtonBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnggota;
    private javax.swing.JButton jButtonBuku;
    private javax.swing.JButton jButtonBuku1;
    private javax.swing.JButton jButtonSkripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
