/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UASPBO;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVRecord;

/**
 *
 * @author RIO
 */
public class TampilSkripsi extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }

    ArrayList<Skripsi> dataSkripsi;

    /**
     * Creates new form TampilSkripsi
     */
    private void tampil() {

        DefaultTableModel model = (DefaultTableModel) jTableSkripsi.getModel();
        model.setRowCount(0);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Skripsi> cq = cb.createQuery(Skripsi.class);
        Root<Skripsi> stud = cq.from(Skripsi.class);
        cq.select(stud.get("nim"));

        CriteriaQuery<Skripsi> select = cq.select(stud);
        TypedQuery<Skripsi> q = em.createQuery(select);
        List<Skripsi> list = q.getResultList();

        for (Skripsi data : list) {
            Object[] baris = new Object[3];
            baris[0] = data.getNim();
            baris[1] = data.getJudulSkripsi();
            baris[2] = data.getTahunSkripsi();

            model.addRow(baris);
        }

        em.getTransaction().commit();
        em.close();
        emf.close();
    }

    public TampilSkripsi() {

        dataSkripsi = new ArrayList<>();
        initComponents();
        tampil();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldTahun = new javax.swing.JTextField();
        jTextFieldNim = new javax.swing.JTextField();
        jTextFieldJudul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSkripsi = new javax.swing.JTable();
        jButtonUpload = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 339, 250, -1));

        jTextFieldNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNimActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 237, 250, -1));
        jPanel1.add(jTextFieldJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 288, 250, -1));

        jLabel3.setText("Judul Skripsi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 292, -1, -1));

        jLabel2.setText("NIM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 238, -1, -1));

        jLabel4.setText("Tahun Skripsi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 343, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA SKRIPSI PERPUSTAKAAN UINSA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 35, -1, -1));

        jButtonSimpan.setBackground(new java.awt.Color(242, 242, 242));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseMoved(evt);
            }
        });
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseExited(evt);
            }
        });
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 511, 110, 50));

        jButtonEdit.setBackground(new java.awt.Color(242, 242, 242));
        jButtonEdit.setText("Edit");
        jButtonEdit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonEditMouseMoved(evt);
            }
        });
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditMouseExited(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 511, 110, 50));

        jButtonHapus.setBackground(new java.awt.Color(242, 242, 242));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseMoved(evt);
            }
        });
        jButtonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseExited(evt);
            }
        });
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 511, 110, 50));

        jButtonCetak.setBackground(new java.awt.Color(242, 242, 242));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseMoved(evt);
            }
        });
        jButtonCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseExited(evt);
            }
        });
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 613, 110, 50));

        jButtonKembali.setBackground(new java.awt.Color(242, 242, 242));
        jButtonKembali.setText("Kembali");
        jButtonKembali.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseMoved(evt);
            }
        });
        jButtonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseExited(evt);
            }
        });
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 613, 110, 50));

        jTableSkripsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "JUDUL", "TAHUN"
            }
        ));
        jTableSkripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSkripsiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSkripsi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 680, 570));

        jButtonUpload.setBackground(new java.awt.Color(242, 242, 242));
        jButtonUpload.setText("Upload");
        jButtonUpload.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseMoved(evt);
            }
        });
        jButtonUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseExited(evt);
            }
        });
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 613, 110, 50));

        jLabel6.setText("Cari");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM", "Judul", "Tahun" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1210, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNimActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            String nim = jTextFieldNim.getText().trim();
            String judul = jTextFieldJudul.getText();
            String tahun = jTextFieldTahun.getText();

            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();

            Skripsi b = new Skripsi();

            b.setNim(nim);
            b.setJudulSkripsi(judul);
            b.setTahunSkripsi(tahun);

            entityManager.persist(b);
            entityManager.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Simpan Gagal");
        }

        jTextFieldNim.setText("");
        jTextFieldJudul.setText("");
        jTextFieldTahun.setText("");

        tampil();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        try {
            String nim = jTextFieldNim.getText().trim();
            String judul = jTextFieldJudul.getText();
            String tahun = jTextFieldTahun.getText();
            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Skripsi b = entityManager.find(Skripsi.class, nim);

            b.setNim(nim);
            b.setJudulSkripsi(judul);
            b.setTahunSkripsi(tahun);

            entityManager.persist(b);
            entityManager.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Ubah Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ubah Gagal");
        }

        jTextFieldNim.setText("");
        jTextFieldJudul.setText("");
        jTextFieldTahun.setText("");

        tampil();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {

            String nim = jTextFieldNim.getText().trim();
            String judul = jTextFieldJudul.getText();
            String tahun = jTextFieldTahun.getText();
            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Skripsi b = entityManager.find(Skripsi.class, nim);

            b.setNim(nim);
            b.setJudulSkripsi(judul);
            b.setTahunSkripsi(tahun);

            entityManager.persist(b);
            entityManager.remove(b);
            entityManager.getTransaction().commit();
            entityManager.close();
            JOptionPane.showMessageDialog(null, "Hapus Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Hapus Gagal");
        }
        jTextFieldNim.setText("");
        jTextFieldJudul.setText("");
        jTextFieldTahun.setText("");

        tampil();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableSkripsi.getModel();
        String searchTerm = jComboBox1.getSelectedItem().toString();
        String selection = jTextFieldCari.getText();
        Map<String,Object> parameter = new HashMap<>();
        parameter.put("searchTerm", searchTerm);
        parameter.put("selection", selection);
        String jrxmlFile = "src/report/reportSkripsi.jrxml";
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = em.createQuery("SELECT s FROM Skripsi s WHERE s.nim LIKE '%" + jTextFieldCari.getText() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = em.createQuery("SELECT s FROM Skripsi s WHERE LOWER(s.judulSkripsi) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = em.createQuery("SELECT s FROM Skripsi s WHERE s.tahunSkripsi LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

        jTextFieldCari.setText("");
        tampil();
        em.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu frameMenu = new Menu();
        frameMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTableSkripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSkripsiMouseClicked
        // TODO add your handling code here:
        int baris = jTableSkripsi.rowAtPoint(evt.getPoint());

        String nim = jTableSkripsi.getValueAt(baris, 0).toString();
        jTextFieldNim.setText(nim);

        String judul = jTableSkripsi.getValueAt(baris, 1).toString();
        jTextFieldJudul.setText(judul);

        String tahun = jTableSkripsi.getValueAt(baris, 2).toString();
        jTextFieldTahun.setText(tahun);
    }//GEN-LAST:event_jTableSkripsiMouseClicked

    private void jButtonSimpanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseMoved
        jButtonSimpan.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonSimpanMouseMoved

    private void jButtonSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseExited
        jButtonSimpan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonSimpanMouseExited

    private void jButtonEditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseMoved
        jButtonEdit.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonEditMouseMoved

    private void jButtonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseExited
        jButtonEdit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonEditMouseExited

    private void jButtonHapusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseMoved
        jButtonHapus.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonHapusMouseMoved

    private void jButtonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseExited
        jButtonHapus.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonHapusMouseExited

    private void jButtonCetakMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseMoved
        jButtonCetak.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonCetakMouseMoved

    private void jButtonCetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseExited
        jButtonCetak.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonCetakMouseExited

    private void jButtonUploadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseMoved
        jButtonUpload.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonUploadMouseMoved

    private void jButtonUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseExited
        jButtonUpload.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonUploadMouseExited

    private void jButtonKembaliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseMoved
        jButtonKembali.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonKembaliMouseMoved

    private void jButtonKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseExited
        jButtonKembali.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonKembaliMouseExited

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        entityManager.getTransaction().begin();

        int i = filechooser.showOpenDialog(null);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = filechooser.getSelectedFile();
            String filepath = f.getPath();
            //Parsing CSV Data

            try {

                InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream(filepath));
                org.apache.commons.csv.CSVParser csvParser = CSVFormat.DEFAULT.parse(inputStreamReader);
                for (CSVRecord csvRecord : csvParser) {
                    Skripsi s = new Skripsi();

                    s.setNim(csvRecord.get(0));
                    s.setJudulSkripsi(csvRecord.get(1));
                    s.setTahunSkripsi(csvRecord.get(2));
                    entityManager.persist(s);

                }
                JOptionPane.showMessageDialog(null, "Upload Berhasil");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Gagal Upload");
            }
            jTextFieldNim.setText("");
            jTextFieldTahun.setText("");
            jTextFieldTahun.setText("");

        }
        entityManager.getTransaction().commit();

        tampil();
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableSkripsi.getModel();
        model.setRowCount(0);

        EntityManager emf = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        emf.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = emf.createQuery("SELECT s FROM Skripsi s WHERE s.nim LIKE '%" + jTextFieldCari.getText() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = emf.createQuery("SELECT s FROM Skripsi s WHERE LOWER(s.judulSkripsi) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = emf.createQuery("SELECT s FROM Skripsi s WHERE s.tahunSkripsi LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Skripsi> result = query.getResultList();
            for (Skripsi skripsi : result) {
                model.addRow(new Object[]{skripsi.getNim(), skripsi.getJudulSkripsi(), skripsi.getTahunSkripsi()});
            }
        }

        emf.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jTextFieldCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilSkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilSkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSkripsi;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldJudul;
    private javax.swing.JTextField jTextFieldNim;
    private javax.swing.JTextField jTextFieldTahun;
    // End of variables declaration//GEN-END:variables
}
