/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UASPBO;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVRecord;
import org.*;

/**
 *
 * @author RIO
 */
public class TampilBuku extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }

    ArrayList<Buku> dataBuku;

    /**
     * Creates new form TampilSkripsi
     */
    private void tampil() {

        DefaultTableModel model = (DefaultTableModel) jTableBuku.getModel();
        model.setRowCount(0);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Buku> cq = cb.createQuery(Buku.class);
        Root<Buku> stud = cq.from(Buku.class);
        cq.select(stud.get("isbn"));

        CriteriaQuery<Buku> select = cq.select(stud);
        TypedQuery<Buku> q = em.createQuery(select);
        List<Buku> list = q.getResultList();

        for (Buku data : list) {
            Object[] baris = new Object[5];
            baris[0] = data.getIsbn();
            baris[1] = data.getJudulBuku();
            baris[2] = data.getTahunTerbit();
            baris[3] = data.getPenerbit();
            baris[4] = data.getKategori();

            model.addRow(baris);
        }

        em.getTransaction().commit();
        em.close();
        emf.close();
    }

    public TampilBuku() {

        dataBuku = new ArrayList<>();
        initComponents();
        tampil();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldTAHUN = new javax.swing.JTextField();
        jTextFieldPENERBIT = new javax.swing.JTextField();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldJUDUL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jButtonUpload = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldKat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldTAHUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 339, 250, -1));
        jPanel1.add(jTextFieldPENERBIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 392, 250, -1));

        jTextFieldISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldISBNActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 237, 250, -1));

        jLabel5.setText("PENERBIT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 396, -1, -1));
        jPanel1.add(jTextFieldJUDUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 288, 250, -1));

        jLabel3.setText("JUDUL BUKU");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 292, -1, -1));

        jLabel2.setText("ISBN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 238, -1, -1));

        jLabel4.setText("TAHUN TERBIT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 343, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA BUKU PERPUSTAKAAN UINSA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 35, -1, -1));

        jButtonSimpan.setBackground(new java.awt.Color(242, 242, 242));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseMoved(evt);
            }
        });
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseExited(evt);
            }
        });
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 511, 110, 50));

        jButtonEdit.setBackground(new java.awt.Color(242, 242, 242));
        jButtonEdit.setText("Edit");
        jButtonEdit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonEditMouseMoved(evt);
            }
        });
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditMouseExited(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 511, 110, 50));

        jButtonHapus.setBackground(new java.awt.Color(242, 242, 242));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseMoved(evt);
            }
        });
        jButtonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseExited(evt);
            }
        });
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 511, 110, 50));

        jButtonCetak.setBackground(new java.awt.Color(242, 242, 242));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseMoved(evt);
            }
        });
        jButtonCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseExited(evt);
            }
        });
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 613, 110, 50));

        jButtonKembali.setBackground(new java.awt.Color(242, 242, 242));
        jButtonKembali.setText("Kembali");
        jButtonKembali.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseMoved(evt);
            }
        });
        jButtonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseExited(evt);
            }
        });
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 613, 110, 50));

        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "JUDUL BUKU", "TAHUN TERBIT", "PENERBIT", "KATEGORI"
            }
        ));
        jTableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuku);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 680, 570));

        jButtonUpload.setBackground(new java.awt.Color(242, 242, 242));
        jButtonUpload.setText("Upload");
        jButtonUpload.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseMoved(evt);
            }
        });
        jButtonUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseExited(evt);
            }
        });
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 613, 110, 50));

        jLabel6.setText("Cari");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISBN", "JUDUL", "TAHUN", "PENERBIT", "KATEGORI" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel7.setText("KATEGORI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));
        jPanel1.add(jTextFieldKat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldISBNActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            String isbn = jTextFieldISBN.getText().trim();
            String judul = jTextFieldJUDUL.getText();
            String tahun = jTextFieldTAHUN.getText();
            String penerbit = jTextFieldPENERBIT.getText();
            String kat = jTextFieldKat.getText();

            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();

            Buku b = new Buku();

            b.setIsbn(isbn);
            b.setJudulBuku(judul);
            b.setTahunTerbit(tahun);
            b.setPenerbit(penerbit);
            b.setKategori(kat);

            entityManager.persist(b);
            entityManager.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Simpan Gagal");
        }

        jTextFieldISBN.setText("");
        jTextFieldJUDUL.setText("");
        jTextFieldTAHUN.setText("");
        jTextFieldPENERBIT.setText("");
        jTextFieldKat.setText("");

        tampil();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        try {
            String isbn = jTextFieldISBN.getText().trim();
            String judul = jTextFieldJUDUL.getText();
            String tahun = jTextFieldTAHUN.getText();
            String penerbit = jTextFieldPENERBIT.getText();
            String kat = jTextFieldKat.getText();

            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Buku b = entityManager.find(Buku.class, isbn);

            b.setIsbn(isbn);
            b.setJudulBuku(judul);
            b.setTahunTerbit(tahun);
            b.setPenerbit(penerbit);
            b.setKategori(kat);

            entityManager.persist(b);
            entityManager.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Ubah Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ubah Gagal");
        }

        jTextFieldISBN.setText("");
        jTextFieldJUDUL.setText("");
        jTextFieldTAHUN.setText("");
        jTextFieldPENERBIT.setText("");
        jTextFieldKat.setText("");

        tampil();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {

            String isbn = jTextFieldISBN.getText().trim();
            String judul = jTextFieldJUDUL.getText();
            String tahun = jTextFieldTAHUN.getText();
            String penerbit = jTextFieldPENERBIT.getText();
            String kat = jTextFieldKat.getText();

            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Buku b = entityManager.find(Buku.class, isbn);

            b.setIsbn(isbn);
            b.setJudulBuku(judul);
            b.setTahunTerbit(tahun);
            b.setPenerbit(penerbit);
            b.setKategori(kat);

            entityManager.persist(b);
            entityManager.remove(b);
            entityManager.getTransaction().commit();
            entityManager.close();
            JOptionPane.showMessageDialog(null, "Hapus Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Hapus Gagal");
        }
        jTextFieldISBN.setText("");
        jTextFieldJUDUL.setText("");
        jTextFieldTAHUN.setText("");
        jTextFieldPENERBIT.setText("");
        jTextFieldKat.setText("");

        tampil();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableBuku.getModel();
        String searchTerm = jComboBox1.getSelectedItem().toString();
        String selection = jTextFieldCari.getText();
        Map<String, Object> parameter = new HashMap<>();
        parameter.put("searchTerm", searchTerm);
        parameter.put("selection", selection);
        String jrxmlFile = "src/report/reportBuku.jrxml";
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = em.createQuery("SELECT b FROM Buku b WHERE b.isbn LIKE '%" + jTextFieldCari.getText() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = em.createQuery("SELECT b FROM Buku b WHERE LOWER(b.judulBuku) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = em.createQuery("SELECT b FROM Buku b WHERE b.tahunTerbit LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jComboBox1.getSelectedIndex() == 3) {
            Query query = em.createQuery("SELECT b FROM Buku b WHERE LOWER(b.penerbit) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jComboBox1.getSelectedIndex() == 4) {
            Query query = em.createQuery("SELECT b FROM Buku b WHERE LOWER(b.kategori) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilBuku.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

        jTextFieldCari.setText("");
        tampil();
        em.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu frameMenu = new Menu();
        frameMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jTableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBukuMouseClicked
        // TODO add your handling code here:
        int baris = jTableBuku.rowAtPoint(evt.getPoint());

        String isbn = jTableBuku.getValueAt(baris, 0).toString();
        jTextFieldISBN.setText(isbn);

        String judul = jTableBuku.getValueAt(baris, 1).toString();
        jTextFieldJUDUL.setText(judul);

        String tahun = jTableBuku.getValueAt(baris, 2).toString();
        jTextFieldTAHUN.setText(tahun);

        String penerbit = jTableBuku.getValueAt(baris, 3).toString();
        jTextFieldPENERBIT.setText(penerbit);
        
        String kat = jTableBuku.getValueAt(baris, 4).toString();
        jTextFieldKat.setText(kat);
    }//GEN-LAST:event_jTableBukuMouseClicked

    private void jButtonSimpanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseMoved
        jButtonSimpan.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonSimpanMouseMoved

    private void jButtonSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseExited
        jButtonSimpan.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonSimpanMouseExited

    private void jButtonEditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseMoved
        jButtonEdit.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonEditMouseMoved

    private void jButtonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseExited
        jButtonEdit.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonEditMouseExited

    private void jButtonHapusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseMoved
        jButtonHapus.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonHapusMouseMoved

    private void jButtonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseExited
        jButtonHapus.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonHapusMouseExited

    private void jButtonCetakMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseMoved
        jButtonCetak.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonCetakMouseMoved

    private void jButtonCetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseExited
        jButtonCetak.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonCetakMouseExited

    private void jButtonUploadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseMoved
        jButtonUpload.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonUploadMouseMoved

    private void jButtonUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseExited
        jButtonUpload.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonUploadMouseExited

    private void jButtonKembaliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseMoved
        jButtonKembali.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonKembaliMouseMoved

    private void jButtonKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseExited
        jButtonKembali.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButtonKembaliMouseExited

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        entityManager.getTransaction().begin();

        int i = filechooser.showOpenDialog(null);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = filechooser.getSelectedFile();
            String filepath = f.getPath();
            //Parsing CSV Data

            try {

                InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream(filepath));
                org.apache.commons.csv.CSVParser csvParser = CSVFormat.DEFAULT.parse(inputStreamReader);
                for (CSVRecord csvRecord : csvParser) {
                    Buku s = new Buku();

                    s.setIsbn(csvRecord.get(0));
                    s.setJudulBuku(csvRecord.get(1));
                    s.setTahunTerbit(csvRecord.get(2));
                    s.setPenerbit(csvRecord.get(3));
                    s.setKategori(csvRecord.get(4));
                    entityManager.persist(s);

                }
                JOptionPane.showMessageDialog(null, "Upload Berhasil");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Gagal Upload");
            }
            jTextFieldISBN.setText("");
            jTextFieldJUDUL.setText("");
            jTextFieldTAHUN.setText("");
            jTextFieldPENERBIT.setText("");
            jTextFieldKat.setText("");

        }
        entityManager.getTransaction().commit();

        tampil();
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableBuku.getModel();
        model.setRowCount(0);

        EntityManager emf = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        emf.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = emf.createQuery("SELECT b FROM Buku b WHERE b.isbn LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = emf.createQuery("SELECT b FROM Buku b WHERE LOWER(b.judulBuku) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = emf.createQuery("SELECT b FROM Buku b WHERE b.tahunTerbit LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
        } else if (jComboBox1.getSelectedIndex() == 3) {
            Query query = emf.createQuery("SELECT b FROM Buku b WHERE LOWER(b.penerbit) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
        } else if (jComboBox1.getSelectedIndex() == 4) {
            Query query = emf.createQuery("SELECT b FROM Buku b WHERE LOWER(b.kategori) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Buku> result = query.getResultList();
            for (Buku buku : result) {
                model.addRow(new Object[]{buku.getIsbn(), buku.getJudulBuku(), buku.getTahunTerbit(), buku.getPenerbit(), buku.getKategori()});
            }
        }

        emf.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jTextFieldCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldJUDUL;
    private javax.swing.JTextField jTextFieldKat;
    private javax.swing.JTextField jTextFieldPENERBIT;
    private javax.swing.JTextField jTextFieldTAHUN;
    // End of variables declaration//GEN-END:variables
}
