/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UASPBO;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVRecord;


/**
 *
 * @author RIO
 */
public class TampilAnggota extends javax.swing.JFrame {

   public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
   
   ArrayList<Anggota> dataAnggota;

    private void tampil() {

        DefaultTableModel model = (DefaultTableModel) jTableAnggota.getModel();
        model.setRowCount(0);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        CriteriaBuilder cb = em.getCriteriaBuilder();
        CriteriaQuery<Anggota> cq = cb.createQuery(Anggota.class);
        Root<Anggota> stud = cq.from(Anggota.class);
        cq.select(stud.get("idAnggota"));

        CriteriaQuery<Anggota> select = cq.select(stud);
        TypedQuery<Anggota> q = em.createQuery(select);
        List<Anggota> list = q.getResultList();

        for (Anggota data : list) {
            Object[] baris = new Object[4];
            baris[0] = data.getIdAnggota();
            baris[1] = data.getNamaAnggota();
            baris[2] = data.getAlamat();
            baris[3] = data.getAngkatan();

            model.addRow(baris);
        }

        em.getTransaction().commit();
        em.close();
        emf.close();
    }
    
    public TampilAnggota() {
        dataAnggota = new ArrayList<>();
        initComponents();
        
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldAlamat = new javax.swing.JTextField();
        jTextFieldNO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnggota = new javax.swing.JTable();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonUpload = new javax.swing.JButton();
        jButtonCetak = new javax.swing.JButton();
        jButtonKembali = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA ANGGOTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 15, -1, -1));

        jLabel2.setText("Cari Anggota");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, -1, -1));

        jTextFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 108, 220, -1));

        jLabel3.setText("ID Anggota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 181, -1, -1));
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 177, 270, -1));

        jLabel4.setText("Nama Anggota");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, -1, -1));

        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 284, -1, -1));

        jLabel6.setText("Angkatan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 340, -1, -1));
        jPanel1.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 226, 270, -1));
        jPanel1.add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 280, 270, -1));
        jPanel1.add(jTextFieldNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 336, 270, -1));

        jTableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Anggota", "Nama", "Alamat", "Angkatan"
            }
        ));
        jTableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnggota);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 108, 592, 590));

        jButtonSimpan.setBackground(new java.awt.Color(242, 242, 242));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseMoved(evt);
            }
        });
        jButtonSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimpanMouseExited(evt);
            }
        });
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 90, 50));

        jButtonHapus.setBackground(new java.awt.Color(242, 242, 242));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseMoved(evt);
            }
        });
        jButtonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHapusMouseExited(evt);
            }
        });
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 90, 50));

        jButtonEdit.setBackground(new java.awt.Color(242, 242, 242));
        jButtonEdit.setText("Edit");
        jButtonEdit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonEditMouseMoved(evt);
            }
        });
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditMouseExited(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 90, 50));

        jButtonUpload.setBackground(new java.awt.Color(242, 242, 242));
        jButtonUpload.setText("Upload");
        jButtonUpload.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseMoved(evt);
            }
        });
        jButtonUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUploadMouseExited(evt);
            }
        });
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 90, 50));

        jButtonCetak.setBackground(new java.awt.Color(242, 242, 242));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseMoved(evt);
            }
        });
        jButtonCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCetakMouseExited(evt);
            }
        });
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 90, 50));

        jButtonKembali.setBackground(new java.awt.Color(242, 242, 242));
        jButtonKembali.setText("Kembali");
        jButtonKembali.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseMoved(evt);
            }
        });
        jButtonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseExited(evt);
            }
        });
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 90, 50));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama", "Alamat", "Telepon" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        try {
            String id = jTextFieldID.getText().trim();
            String nama = jTextFieldNama.getText();
            String alamat = jTextFieldAlamat.getText();
            String nomor = jTextFieldNO.getText();

            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();

            Anggota b = new Anggota();

            b.setIdAnggota(id);
            b.setNamaAnggota(nama);
            b.setAlamat(alamat);
            b.setAngkatan(nomor);

            entityManager.persist(b);
            entityManager.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Simpan Gagal");
        }

        jTextFieldID.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldNO.setText("");

        tampil();
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            String id = jTextFieldID.getText().trim();
            String nama = jTextFieldNama.getText();
            String alamat = jTextFieldAlamat.getText();
            String nomor = jTextFieldNO.getText();
            
            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Anggota b = entityManager.find(Anggota.class, id);

            b.setIdAnggota(id);
            b.setNamaAnggota(nama);
            b.setAlamat(alamat);
            b.setAngkatan(nomor);

            entityManager.persist(b);
            entityManager.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Ubah Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ubah Gagal");
        }

        jTextFieldID.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldNO.setText("");

        tampil();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        try {

            String id = jTextFieldID.getText().trim();
            String nama = jTextFieldNama.getText();
            String alamat = jTextFieldAlamat.getText();
            String nomor = jTextFieldNO.getText();
            
            EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

            entityManager.getTransaction().begin();
            Anggota b = entityManager.find(Anggota.class,id);

            b.setIdAnggota(id);
            b.setNamaAnggota(nama);
            b.setAlamat(alamat);
            b.setAngkatan(nomor);

            entityManager.persist(b);
            entityManager.remove(b);
            entityManager.getTransaction().commit();
            entityManager.close();
            JOptionPane.showMessageDialog(null, "Hapus Berhasil");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Hapus Gagal");
        }
        
        jTextFieldID.setText("");
        jTextFieldNama.setText("");
        jTextFieldAlamat.setText("");
        jTextFieldNO.setText("");

        tampil();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jTableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnggotaMouseClicked
        int baris = jTableAnggota.rowAtPoint(evt.getPoint());

        String id = jTableAnggota.getValueAt(baris, 0).toString();
        jTextFieldID.setText(id);

        String nama = jTableAnggota.getValueAt(baris, 1).toString();
        jTextFieldNama.setText(nama);

        String alamat = jTableAnggota.getValueAt(baris, 2).toString();
        jTextFieldAlamat.setText(alamat);

        String nomor = jTableAnggota.getValueAt(baris, 3).toString();
        jTextFieldNO.setText(nomor);
    }//GEN-LAST:event_jTableAnggotaMouseClicked

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        JFileChooser filechooser = new JFileChooser();
        EntityManager entityManager = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        entityManager.getTransaction().begin();

        int i = filechooser.showOpenDialog(null);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = filechooser.getSelectedFile();
            String filepath = f.getPath();
            //Parsing CSV Data

            try {

                InputStreamReader inputStreamReader = new InputStreamReader(new FileInputStream(filepath));
                org.apache.commons.csv.CSVParser csvParser = CSVFormat.DEFAULT.parse(inputStreamReader);
                for (CSVRecord csvRecord : csvParser) {
                    Anggota a = new Anggota();

                    a.setIdAnggota(csvRecord.get(0));
                    a.setNamaAnggota(csvRecord.get(1));
                    a.setAlamat(csvRecord.get(2));
                    a.setAngkatan(csvRecord.get(3));
                    entityManager.persist(a);

                }
                JOptionPane.showMessageDialog(null, "Upload Berhasil");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Gagal Upload");
            }
            jTextFieldID.setText("");
            jTextFieldNama.setText("");
            jTextFieldAlamat.setText("");
            jTextFieldNO.setText("");

        }
        entityManager.getTransaction().commit();

        tampil();
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        this.hide();
        Menu frameMenu = new Menu();
        frameMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonSimpanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseMoved
        jButtonSimpan.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonSimpanMouseMoved

    private void jButtonSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimpanMouseExited
        jButtonSimpan.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonSimpanMouseExited

    private void jButtonHapusMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseMoved
        jButtonHapus.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonHapusMouseMoved

    private void jButtonHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHapusMouseExited
        jButtonHapus.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonHapusMouseExited

    private void jButtonEditMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseMoved
        jButtonEdit.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonEditMouseMoved

    private void jButtonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseExited
        jButtonEdit.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonEditMouseExited

    private void jButtonUploadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseMoved
        jButtonUpload.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonUploadMouseMoved

    private void jButtonUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUploadMouseExited
        jButtonUpload.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonUploadMouseExited

    private void jButtonCetakMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseMoved
        jButtonCetak.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonCetakMouseMoved

    private void jButtonCetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCetakMouseExited
        jButtonCetak.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonCetakMouseExited

    private void jButtonKembaliMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseMoved
        jButtonKembali.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButtonKembaliMouseMoved

    private void jButtonKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseExited
        jButtonKembali.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButtonKembaliMouseExited

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableAnggota.getModel();
        String searchTerm = jComboBox1.getSelectedItem().toString();
        String selection = jTextFieldCari.getText();
        Map<String, Object> parameter = new HashMap<>();
           parameter.put("searchTerm", searchTerm);
           parameter.put("selection", selection);
        String jrxmlFile = "src/report/reportAnggota.jrxml";
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UASPBOPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = em.createQuery("SELECT a FROM Anggota a WHERE a.idAnggota LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilAnggota.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = em.createQuery("SELECT a FROM Anggota a WHERE LOWER(a.namaAnggota) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilAnggota.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = em.createQuery("SELECT a FROM Anggota a WHERE (a.alamat) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilAnggota.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (jComboBox1.getSelectedIndex() == 3) {
            Query query = em.createQuery("SELECT a FROM Anggota a WHERE a.angkatan LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(result);

            try {
                // TODO add your handling code here:
                JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, dataSource);
                JasperViewer jv = new JasperViewer(jp, false);
                jv.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TampilAnggota.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
            
        }

        jTextFieldCari.setText("");
        tampil();
        em.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jButtonCetakActionPerformed

    private void jTextFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTableAnggota.getModel();
        model.setRowCount(0);

        EntityManager emf = Persistence.createEntityManagerFactory("UASPBOPU").createEntityManager();

        emf.getTransaction().begin();

        if (jComboBox1.getSelectedIndex() == 0) {
            Query query = emf.createQuery("SELECT a FROM Anggota a WHERE a.idAnggota LIKE '%" + jTextFieldCari.getText() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            
        } else if (jComboBox1.getSelectedIndex() == 1) {
            Query query = emf.createQuery("SELECT a FROM Anggota a WHERE LOWER(a.namaAnggota) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            
        } else if (jComboBox1.getSelectedIndex() == 2) {
            Query query = emf.createQuery("SELECT a FROM Anggota a WHERE LOWER(a.alamat) LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
            
        } else if (jComboBox1.getSelectedIndex() == 3) {
            Query query = emf.createQuery("SELECT a FROM Anggota a WHERE a.angkatan LIKE '%" + jTextFieldCari.getText().toLowerCase() + "%'");
            List<Anggota> result = query.getResultList();
            for (Anggota anggota : result) {
                model.addRow(new Object[]{anggota.getIdAnggota(), anggota.getNamaAnggota(), anggota.getAlamat(), anggota.getAngkatan()});
            }
    
        }

        emf.getTransaction().commit();

        emf.close();
    }//GEN-LAST:event_jTextFieldCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnggota;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNO;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
